// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aprvjwqzzrabxegnwrei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwcnZqd3F6enJhYnhlZ253cmVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzkzMDcsImV4cCI6MjA3MDA1NTMwN30.HyiCTZVWyu4WJIc7zcEf-qoJ938RoDm1P_payX0OzKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});